const TWITTER_IDS = {
  BOUT_BOT_ID: '3016652708',
  BOUT_BETA_ID: '2578652522'
}

const REPLY_TYPES = {
  YOU_WIN: 'YOU_WIN',
  MOVE_SUCCESS: 'MOVE_SUCCESS',
  MOVE_FAILED: 'MOVE_FAILED',
  MOVE_INVALID: 'MOVE_INVALID',
  NO_MOVE: 'NO_MOVE',
  NEXT_TURN: 'NEXT_TURN',
  TRY_AGAIN: 'TRY_AGAIN',
  YOU_LOSE: 'YOU_LOSE'
}

module.exports = {
  TWITTER_IDS,
  REPLY_TYPES
}
