const TWITTER_IDS = {
  // BOUT_BOT_ID: '3016652708', // Twitter
  BOUT_BOT_ID: "109790228461724273", // Mastodon
};

const REPLY_TYPES = {
  YOU_WIN: "YOU_WIN",
  MOVE_SUCCESS: "MOVE_SUCCESS",
  MOVE_FAILED: "MOVE_FAILED",
  MOVE_INVALID: "MOVE_INVALID",
  NO_MOVE: "NO_MOVE",
  NEXT_TURN: "NEXT_TURN",
  TRY_AGAIN: "TRY_AGAIN",
  YOU_LOSE: "YOU_LOSE",
};

module.exports = {
  TWITTER_IDS,
  REPLY_TYPES,
};
