const tweets = [
  {
    created_at: 'Sat Aug 19 03:55:09 +0000 2017', // KEEP
    id: 898755188797751300,
    id_str: '898755188797751296', // KEEP
    text: '@bout_bot challenge @sweetdeethecat', // KEEP
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: 'bout_bot', // KEEP
          name: 'Bout',
          id: 2578652522,
          id_str: '2578652522', // KEEP
          indices: [0, 9]
        }, {
          screen_name: 'sweetdeethecat',
          name: 'Sweet Dee',
          id: 2291790446,
          id_str: '2291790446',
          indices: [20, 35]
        }
      ], // KEEP
      urls: []
    },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 2578652522,
    in_reply_to_user_id_str: '2578652522',
    in_reply_to_screen_name: 'bout_bot',
    user: {
      id: 15332057,
      id_str: '15332057', // KEEP
      name: 'Michael Knepprath', // KEEP
      screen_name: 'mknepprath', // KEEP
      location: 'Mankato, MN',
      description: 'Developer @WHCCpro and builder of bots: @familiarlilt / @designprompts / @robot_mk',
      url: 'https://t.co/utBZAnmX5C',
      entities: [Object],
      protected: false,
      followers_count: 760,
      friends_count: 272,
      listed_count: 63,
      created_at: 'Sun Jul 06 10:59:37 +0000 2008',
      favourites_count: 40328,
      utc_offset: -18000,
      time_zone: 'Central Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 26213,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '26D8D2',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/15332057/1491605515',
      profile_link_color: '3F0CE8',
      profile_sidebar_border_color: 'BBBCBE',
      profile_sidebar_fill_color: 'EEEEEE',
      profile_text_color: '766666',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en'
  }, {
    created_at: 'Fri Aug 18 04:30:16 +0000 2017',
    id: 898401638351724500,
    id_str: '898401638351724544',
    text: '@bout_bot @sweetdeethecat #throw',
    truncated: false,
    entities: {
      hashtags: [Object],
      symbols: [],
      user_mentions: [
        {
          screen_name: 'bout_bot',
          name: 'Bout',
          id: 2578652522,
          id_str: '2578652522',
          indices: [0, 9]
        }, {
          screen_name: 'sweetdeethecat',
          name: 'Sweet Dee',
          id: 2291790446,
          id_str: '2291790446',
          indices: [10, 25]
        }
      ],
      urls: []
    },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: 898401387393859600,
    in_reply_to_status_id_str: '898401387393859584',
    in_reply_to_user_id: 2578652522,
    in_reply_to_user_id_str: '2578652522',
    in_reply_to_screen_name: 'bout_bot',
    user: {
      id: 15332057,
      id_str: '15332057',
      name: 'Michael Knepprath',
      screen_name: 'mknepprath',
      location: 'Mankato, MN',
      description: 'Developer @WHCCpro and builder of bots: @familiarlilt / @designprompts / @robot_mk',
      url: 'https://t.co/utBZAnmX5C',
      entities: [Object],
      protected: false,
      followers_count: 760,
      friends_count: 272,
      listed_count: 63,
      created_at: 'Sun Jul 06 10:59:37 +0000 2008',
      favourites_count: 40328,
      utc_offset: -18000,
      time_zone: 'Central Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 26213,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '26D8D2',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/15332057/1491605515',
      profile_link_color: '3F0CE8',
      profile_sidebar_border_color: 'BBBCBE',
      profile_sidebar_fill_color: 'EEEEEE',
      profile_text_color: '766666',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'und'
  }, {
    created_at: 'Fri Aug 18 04:29:14 +0000 2017',
    id: 898401378283929600,
    id_str: '898401378283929600',
    text: '@bout_bot @mknepprath #swing',
    truncated: false,
    entities: {
      hashtags: [Object],
      symbols: [],
      user_mentions: [
        {
          screen_name: 'bout_bot',
          name: 'Bout',
          id: 2578652522,
          id_str: '2578652522',
          indices: [0, 9]
        }, {
          screen_name: 'mknepprath',
          name: 'Michael Knepprath',
          id: 15332057,
          id_str: '15332057',
          indices: [10, 21]
        }
      ],
      urls: []
    },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: 898018234259124200,
    in_reply_to_status_id_str: '898018234259124226',
    in_reply_to_user_id: 2578652522,
    in_reply_to_user_id_str: '2578652522',
    in_reply_to_screen_name: 'bout_bot',
    user: {
      id: 2291790446,
      id_str: '2291790446',
      name: 'Sweet Dee',
      screen_name: 'sweetdeethecat',
      location: 'Mankato, MN',
      description: 'meow',
      url: null,
      entities: [Object],
      protected: false,
      followers_count: 3,
      friends_count: 1,
      listed_count: 0,
      created_at: 'Tue Jan 14 22:41:15 +0000 2014',
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 28,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '000000',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/423224104255111168/Vq_-ogaC_normal.jpeg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/423224104255111168/Vq_-ogaC_normal.jpeg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/2291790446/1411088008',
      profile_link_color: 'A03B27',
      profile_sidebar_border_color: '000000',
      profile_sidebar_fill_color: '000000',
      profile_text_color: '000000',
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'und'
  }, {
    created_at: 'Thu Aug 17 03:06:33 +0000 2017',
    id: 898018181905698800,
    id_str: '898018181905698819',
    text: '@bout_bot I challenge @sweetdeethecat',
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: 'bout_bot',
          name: 'Bout',
          id: 2578652522,
          id_str: '2578652522',
          indices: [0, 9]
        }, {
          screen_name: 'sweetdeethecat',
          name: 'Sweet Dee',
          id: 2291790446,
          id_str: '2291790446',
          indices: [22, 37]
        }
      ],
      urls: []
    },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 2578652522,
    in_reply_to_user_id_str: '2578652522',
    in_reply_to_screen_name: 'bout_bot',
    user: {
      id: 15332057,
      id_str: '15332057',
      name: 'Michael Knepprath',
      screen_name: 'mknepprath',
      location: 'Mankato, MN',
      description: 'Developer @WHCCpro and builder of bots: @familiarlilt / @designprompts / @robot_mk',
      url: 'https://t.co/utBZAnmX5C',
      entities: [Object],
      protected: false,
      followers_count: 760,
      friends_count: 272,
      listed_count: 63,
      created_at: 'Sun Jul 06 10:59:37 +0000 2008',
      favourites_count: 40328,
      utc_offset: -18000,
      time_zone: 'Central Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 26213,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '26D8D2',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/15332057/1491605515',
      profile_link_color: '3F0CE8',
      profile_sidebar_border_color: 'BBBCBE',
      profile_sidebar_fill_color: 'EEEEEE',
      profile_text_color: '766666',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en'
  }, {
    created_at: 'Tue Jul 25 05:10:48 +0000 2017',
    id: 889714527545241600,
    id_str: '889714527545241601',
    text: '@bout_bot Did a little more work - haven\'t touched the styles yet (I swear it will look better soon!) Pushed my lat… https://t.co/75rDc0ZRMc',
    truncated: true,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [
        {
          screen_name: 'bout_bot',
          name: 'Bout',
          id: 2578652522,
          id_str: '2578652522',
          indices: [0, 9]
        }
      ],
      urls: [Object]
    },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: 889353018403160000,
    in_reply_to_status_id_str: '889353018403160065',
    in_reply_to_user_id: 15332057,
    in_reply_to_user_id_str: '15332057',
    in_reply_to_screen_name: 'mknepprath',
    user: {
      id: 15332057,
      id_str: '15332057',
      name: 'Michael Knepprath',
      screen_name: 'mknepprath',
      location: 'Mankato, MN',
      description: 'Developer @WHCCpro and builder of bots: @familiarlilt / @designprompts / @robot_mk',
      url: 'https://t.co/utBZAnmX5C',
      entities: [Object],
      protected: false,
      followers_count: 760,
      friends_count: 272,
      listed_count: 63,
      created_at: 'Sun Jul 06 10:59:37 +0000 2008',
      favourites_count: 40328,
      utc_offset: -18000,
      time_zone: 'Central Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 26213,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '26D8D2',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/15332057/1491605515',
      profile_link_color: '3F0CE8',
      profile_sidebar_border_color: 'BBBCBE',
      profile_sidebar_fill_color: 'EEEEEE',
      profile_text_color: '766666',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en'
  }, {
    created_at: 'Mon Jul 24 05:41:43 +0000 2017',
    id: 889359920104996900,
    id_str: '889359920104996864',
    text: '@mknepprath @bout_bot Hah its a fight to the… eer an endless fight for all eternity!',
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [Object],
      urls: []
    },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: 889153389996761100,
    in_reply_to_status_id_str: '889153389996761090',
    in_reply_to_user_id: 15332057,
    in_reply_to_user_id_str: '15332057',
    in_reply_to_screen_name: 'mknepprath',
    user: {
      id: 19697831,
      id_str: '19697831',
      name: 'Kevin Gutowski',
      screen_name: 'kevgski',
      location: 'Berkeley, CA',
      description: 'Half-snack Pixel Miner at @Gradescope. while(always distracted) { C4D renders + D3 + Interactive physics textbook + music (composition, engraving, & violin) }',
      url: 'https://t.co/WL41WNpYjB',
      entities: [Object],
      protected: false,
      followers_count: 239,
      friends_count: 871,
      listed_count: 7,
      created_at: 'Thu Jan 29 05:34:56 +0000 2009',
      favourites_count: 2883,
      utc_offset: -25200,
      time_zone: 'Pacific Time (US & Canada)',
      geo_enabled: false,
      verified: false,
      statuses_count: 2957,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '000000',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/24262626/vladstudio_piano_1152x864.jpg',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/24262626/vladstudio_piano_1152x864.jpg',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/887724427919499265/d9Mrm7OV_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/887724427919499265/d9Mrm7OV_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/19697831/1428953702',
      profile_link_color: '3477C9',
      profile_sidebar_border_color: '000000',
      profile_sidebar_fill_color: '2EB9FF',
      profile_text_color: '080545',
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    lang: 'en'
  }, {
    created_at: 'Mon Jul 24 05:24:53 +0000 2017',
    id: 889355686554910700,
    id_str: '889355686554910720',
    text: '@mknepprath @bout_bot yay!',
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [Object],
      urls: []
    },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: 889353018403160000,
    in_reply_to_status_id_str: '889353018403160065',
    in_reply_to_user_id: 15332057,
    in_reply_to_user_id_str: '15332057',
    in_reply_to_screen_name: 'mknepprath',
    user: {
      id: 2451223458,
      id_str: '2451223458',
      name: 'Max Stoiber',
      screen_name: 'mxstbr',
      location: 'Vienna, Austria',
      description: 'Cofounder @withspectrum ✌️ Makes styled-components, react-boilerplate and micro-analytics 💅 Speciality coffee geek, skier, traveller ☕https://t.co/3PKeJrDbU8',
      url: 'https://t.co/AAbfKphHwn',
      entities: [Object],
      protected: false,
      followers_count: 11844,
      friends_count: 1169,
      listed_count: 457,
      created_at: 'Fri Apr 18 11:17:26 +0000 2014',
      favourites_count: 32017,
      utc_offset: 7200,
      time_zone: 'Belgrade',
      geo_enabled: false,
      verified: false,
      statuses_count: 24040,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: 'EEEEEE',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/763033229993574400/6frGyDyA_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/763033229993574400/6frGyDyA_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/2451223458/1479507323',
      profile_link_color: '1B95E0',
      profile_sidebar_border_color: '000000',
      profile_sidebar_fill_color: '000000',
      profile_text_color: '000000',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    lang: 'und'
  }, {
    created_at: 'Mon Jul 24 05:14:17 +0000 2017',
    id: 889353018403160000,
    id_str: '889353018403160065',
    text: '@bout_bot Progress today... not pretty, but I\'m now using styled-components https://t.co/z0CFC02DAp',
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [Object],
      urls: [],
      media: [Object]
    },
    extended_entities: {
      media: [Object]
    },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: 889153389996761100,
    in_reply_to_status_id_str: '889153389996761090',
    in_reply_to_user_id: 15332057,
    in_reply_to_user_id_str: '15332057',
    in_reply_to_screen_name: 'mknepprath',
    user: {
      id: 15332057,
      id_str: '15332057',
      name: 'Michael Knepprath',
      screen_name: 'mknepprath',
      location: 'Mankato, MN',
      description: 'Developer @WHCCpro and builder of bots: @familiarlilt / @designprompts / @robot_mk',
      url: 'https://t.co/utBZAnmX5C',
      entities: [Object],
      protected: false,
      followers_count: 760,
      friends_count: 272,
      listed_count: 63,
      created_at: 'Sun Jul 06 10:59:37 +0000 2008',
      favourites_count: 40328,
      utc_offset: -18000,
      time_zone: 'Central Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 26213,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '26D8D2',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/15332057/1491605515',
      profile_link_color: '3F0CE8',
      profile_sidebar_border_color: 'BBBCBE',
      profile_sidebar_fill_color: 'EEEEEE',
      profile_text_color: '766666',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 1,
    favorite_count: 5,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en'
  }, {
    created_at: 'Sun Jul 23 21:43:02 +0000 2017',
    id: 889239456791789600,
    id_str: '889239456791789569',
    text: '@crc @bout_bot I\'ll be posting updates as I make progress - thanks for checking it out!',
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [Object],
      urls: []
    },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: 889239054151290900,
    in_reply_to_status_id_str: '889239054151290880',
    in_reply_to_user_id: 3259381,
    in_reply_to_user_id_str: '3259381',
    in_reply_to_screen_name: 'crc',
    user: {
      id: 15332057,
      id_str: '15332057',
      name: 'Michael Knepprath',
      screen_name: 'mknepprath',
      location: 'Mankato, MN',
      description: 'Developer @WHCCpro and builder of bots: @familiarlilt / @designprompts / @robot_mk',
      url: 'https://t.co/utBZAnmX5C',
      entities: [Object],
      protected: false,
      followers_count: 760,
      friends_count: 272,
      listed_count: 63,
      created_at: 'Sun Jul 06 10:59:37 +0000 2008',
      favourites_count: 40328,
      utc_offset: -18000,
      time_zone: 'Central Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 26213,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '26D8D2',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/15332057/1491605515',
      profile_link_color: '3F0CE8',
      profile_sidebar_border_color: 'BBBCBE',
      profile_sidebar_fill_color: 'EEEEEE',
      profile_text_color: '766666',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en'
  }, {
    created_at: 'Sun Jul 23 21:41:26 +0000 2017',
    id: 889239054151290900,
    id_str: '889239054151290880',
    text: '@mknepprath @bout_bot Regardless, it was a fun distraction to swing swords and throw rocks from the coffee shop I\'m sitting in! 😛',
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [Object],
      urls: []
    },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: 889238816854331400,
    in_reply_to_status_id_str: '889238816854331396',
    in_reply_to_user_id: 15332057,
    in_reply_to_user_id_str: '15332057',
    in_reply_to_screen_name: 'mknepprath',
    user: {
      id: 3259381,
      id_str: '3259381',
      name: 'Chris Castle',
      screen_name: 'crc',
      location: 'Seattle, WA',
      description: 'heroku developer advocate, enabler, cyclist, skier. lover of learning and cold weather. admirer of MWT (mnts, water, & trails).',
      url: 'https://t.co/G2F6uMdtTD',
      entities: [Object],
      protected: false,
      followers_count: 1047,
      friends_count: 1512,
      listed_count: 50,
      created_at: 'Mon Apr 02 22:58:00 +0000 2007',
      favourites_count: 4393,
      utc_offset: -25200,
      time_zone: 'Pacific Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 4892,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: 'DD2E44',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/679079426953363456/HjTLlHvY_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/679079426953363456/HjTLlHvY_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/3259381/1450739598',
      profile_link_color: 'ABB8C2',
      profile_sidebar_border_color: '87BC44',
      profile_sidebar_fill_color: 'E0FF92',
      profile_text_color: '000000',
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    lang: 'en'
  }, {
    created_at: 'Sun Jul 23 21:40:29 +0000 2017',
    id: 889238816854331400,
    id_str: '889238816854331396',
    text: '@crc @bout_bot Suffice it to say, there are a lot of pieces not quite in place yet 😉',
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [Object],
      urls: []
    },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: 889238592806985700,
    in_reply_to_status_id_str: '889238592806985728',
    in_reply_to_user_id: 3259381,
    in_reply_to_user_id_str: '3259381',
    in_reply_to_screen_name: 'crc',
    user: {
      id: 15332057,
      id_str: '15332057',
      name: 'Michael Knepprath',
      screen_name: 'mknepprath',
      location: 'Mankato, MN',
      description: 'Developer @WHCCpro and builder of bots: @familiarlilt / @designprompts / @robot_mk',
      url: 'https://t.co/utBZAnmX5C',
      entities: [Object],
      protected: false,
      followers_count: 760,
      friends_count: 272,
      listed_count: 63,
      created_at: 'Sun Jul 06 10:59:37 +0000 2008',
      favourites_count: 40328,
      utc_offset: -18000,
      time_zone: 'Central Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 26213,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '26D8D2',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/15332057/1491605515',
      profile_link_color: '3F0CE8',
      profile_sidebar_border_color: 'BBBCBE',
      profile_sidebar_fill_color: 'EEEEEE',
      profile_text_color: '766666',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en'
  }, {
    created_at: 'Sun Jul 23 21:39:36 +0000 2017',
    id: 889238592806985700,
    id_str: '889238592806985728',
    text: '@mknepprath @bout_bot I got negative health, I must be invincible!',
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [Object],
      urls: []
    },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: 889153389996761100,
    in_reply_to_status_id_str: '889153389996761090',
    in_reply_to_user_id: 15332057,
    in_reply_to_user_id_str: '15332057',
    in_reply_to_screen_name: 'mknepprath',
    user: {
      id: 3259381,
      id_str: '3259381',
      name: 'Chris Castle',
      screen_name: 'crc',
      location: 'Seattle, WA',
      description: 'heroku developer advocate, enabler, cyclist, skier. lover of learning and cold weather. admirer of MWT (mnts, water, & trails).',
      url: 'https://t.co/G2F6uMdtTD',
      entities: [Object],
      protected: false,
      followers_count: 1047,
      friends_count: 1512,
      listed_count: 50,
      created_at: 'Mon Apr 02 22:58:00 +0000 2007',
      favourites_count: 4393,
      utc_offset: -25200,
      time_zone: 'Pacific Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 4892,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: 'DD2E44',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/679079426953363456/HjTLlHvY_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/679079426953363456/HjTLlHvY_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/3259381/1450739598',
      profile_link_color: 'ABB8C2',
      profile_sidebar_border_color: '87BC44',
      profile_sidebar_fill_color: 'E0FF92',
      profile_text_color: '000000',
      profile_use_background_image: true,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 1,
    favorited: false,
    retweeted: false,
    lang: 'en'
  }, {
    created_at: 'Sun Jul 23 16:01:02 +0000 2017',
    id: 889153389996761100,
    id_str: '889153389996761090',
    text: 'Working on @bout_bot again - starting over with CRA + Heroku. Simple demo @ https://t.co/DVJ9LPjCjb (open your cons… https://t.co/O9NABdCsh9',
    truncated: true,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [Object],
      urls: [Object]
    },
    source: '<a href="http://twitter.com" rel="nofollow">Twitter Web Client</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: null,
    in_reply_to_user_id_str: null,
    in_reply_to_screen_name: null,
    user: {
      id: 15332057,
      id_str: '15332057',
      name: 'Michael Knepprath',
      screen_name: 'mknepprath',
      location: 'Mankato, MN',
      description: 'Developer @WHCCpro and builder of bots: @familiarlilt / @designprompts / @robot_mk',
      url: 'https://t.co/utBZAnmX5C',
      entities: [Object],
      protected: false,
      followers_count: 760,
      friends_count: 272,
      listed_count: 63,
      created_at: 'Sun Jul 06 10:59:37 +0000 2008',
      favourites_count: 40328,
      utc_offset: -18000,
      time_zone: 'Central Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 26213,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '26D8D2',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/15332057/1491605515',
      profile_link_color: '3F0CE8',
      profile_sidebar_border_color: 'BBBCBE',
      profile_sidebar_fill_color: 'EEEEEE',
      profile_text_color: '766666',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 2,
    favorited: false,
    retweeted: false,
    possibly_sensitive: false,
    lang: 'en'
  }, {
    created_at: 'Fri Jun 16 21:39:43 +0000 2017',
    id: 875830273178456000,
    id_str: '875830273178456065',
    text: '@notwaldorf ahh didn\'t send that one either, that\'s @FamiliarLilt! @bout_bot lets you "battle" folks - currently not running due to 🐜🐞🕷',
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [Object],
      urls: []
    },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: 875829250246488000,
    in_reply_to_status_id_str: '875829250246488065',
    in_reply_to_user_id: 167834639,
    in_reply_to_user_id_str: '167834639',
    in_reply_to_screen_name: 'notwaldorf',
    user: {
      id: 15332057,
      id_str: '15332057',
      name: 'Michael Knepprath',
      screen_name: 'mknepprath',
      location: 'Mankato, MN',
      description: 'Developer @WHCCpro and builder of bots: @familiarlilt / @designprompts / @robot_mk',
      url: 'https://t.co/utBZAnmX5C',
      entities: [Object],
      protected: false,
      followers_count: 760,
      friends_count: 272,
      listed_count: 63,
      created_at: 'Sun Jul 06 10:59:37 +0000 2008',
      favourites_count: 40328,
      utc_offset: -18000,
      time_zone: 'Central Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 26213,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '26D8D2',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/15332057/1491605515',
      profile_link_color: '3F0CE8',
      profile_sidebar_border_color: 'BBBCBE',
      profile_sidebar_fill_color: 'EEEEEE',
      profile_text_color: '766666',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en'
  }, {
    created_at: 'Sat Apr 15 19:58:51 +0000 2017',
    id: 853336837921886200,
    id_str: '853336837921886208',
    text: '@bout_bot @sweetdeethecat so #swing that stick',
    truncated: false,
    entities: {
      hashtags: [Object],
      symbols: [],
      user_mentions: [Object],
      urls: []
    },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: 853336481372524500,
    in_reply_to_status_id_str: '853336481372524544',
    in_reply_to_user_id: 2578652522,
    in_reply_to_user_id_str: '2578652522',
    in_reply_to_screen_name: 'bout_bot',
    user: {
      id: 15332057,
      id_str: '15332057',
      name: 'Michael Knepprath',
      screen_name: 'mknepprath',
      location: 'Mankato, MN',
      description: 'Developer @WHCCpro and builder of bots: @familiarlilt / @designprompts / @robot_mk',
      url: 'https://t.co/utBZAnmX5C',
      entities: [Object],
      protected: false,
      followers_count: 760,
      friends_count: 272,
      listed_count: 63,
      created_at: 'Sun Jul 06 10:59:37 +0000 2008',
      favourites_count: 40328,
      utc_offset: -18000,
      time_zone: 'Central Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 26213,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '26D8D2',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/15332057/1491605515',
      profile_link_color: '3F0CE8',
      profile_sidebar_border_color: 'BBBCBE',
      profile_sidebar_fill_color: 'EEEEEE',
      profile_text_color: '766666',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en'
  }, {
    created_at: 'Sat Apr 15 19:57:13 +0000 2017',
    id: 853336428020985900,
    id_str: '853336428020985856',
    text: '@bout_bot challenge @sweetdeethecat',
    truncated: false,
    entities: {
      hashtags: [],
      symbols: [],
      user_mentions: [Object],
      urls: []
    },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 2578652522,
    in_reply_to_user_id_str: '2578652522',
    in_reply_to_screen_name: 'bout_bot',
    user: {
      id: 15332057,
      id_str: '15332057',
      name: 'Michael Knepprath',
      screen_name: 'mknepprath',
      location: 'Mankato, MN',
      description: 'Developer @WHCCpro and builder of bots: @familiarlilt / @designprompts / @robot_mk',
      url: 'https://t.co/utBZAnmX5C',
      entities: [Object],
      protected: false,
      followers_count: 760,
      friends_count: 272,
      listed_count: 63,
      created_at: 'Sun Jul 06 10:59:37 +0000 2008',
      favourites_count: 40328,
      utc_offset: -18000,
      time_zone: 'Central Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 26213,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '26D8D2',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/15332057/1491605515',
      profile_link_color: '3F0CE8',
      profile_sidebar_border_color: 'BBBCBE',
      profile_sidebar_fill_color: 'EEEEEE',
      profile_text_color: '766666',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en'
  }, {
    created_at: 'Sat Apr 15 16:49:17 +0000 2017',
    id: 853289135125270500,
    id_str: '853289135125270529',
    text: '@bout_bot @sweetdeethecat I will also #throw',
    truncated: false,
    entities: {
      hashtags: [Object],
      symbols: [],
      user_mentions: [Object],
      urls: []
    },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: 853288779741892600,
    in_reply_to_status_id_str: '853288779741892608',
    in_reply_to_user_id: 2578652522,
    in_reply_to_user_id_str: '2578652522',
    in_reply_to_screen_name: 'bout_bot',
    user: {
      id: 15332057,
      id_str: '15332057',
      name: 'Michael Knepprath',
      screen_name: 'mknepprath',
      location: 'Mankato, MN',
      description: 'Developer @WHCCpro and builder of bots: @familiarlilt / @designprompts / @robot_mk',
      url: 'https://t.co/utBZAnmX5C',
      entities: [Object],
      protected: false,
      followers_count: 760,
      friends_count: 272,
      listed_count: 63,
      created_at: 'Sun Jul 06 10:59:37 +0000 2008',
      favourites_count: 40328,
      utc_offset: -18000,
      time_zone: 'Central Time (US & Canada)',
      geo_enabled: true,
      verified: false,
      statuses_count: 26213,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '26D8D2',
      profile_background_image_url: 'http://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_image_url_https: 'https://pbs.twimg.com/profile_background_images/355201067/bg.gif',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/879095121278402560/M2jj3ag0_normal.jpg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/15332057/1491605515',
      profile_link_color: '3F0CE8',
      profile_sidebar_border_color: 'BBBCBE',
      profile_sidebar_fill_color: 'EEEEEE',
      profile_text_color: '766666',
      profile_use_background_image: false,
      has_extended_profile: true,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'en'
  }, {
    created_at: 'Sat Apr 15 16:43:33 +0000 2017',
    id: 853287691521318900,
    id_str: '853287691521318912',
    text: '@bout_bot  @mknepprath #throw...',
    truncated: false,
    entities: {
      hashtags: [Object],
      symbols: [],
      user_mentions: [Object],
      urls: []
    },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: null,
    in_reply_to_status_id_str: null,
    in_reply_to_user_id: 2578652522,
    in_reply_to_user_id_str: '2578652522',
    in_reply_to_screen_name: 'bout_bot',
    user: {
      id: 2291790446,
      id_str: '2291790446',
      name: 'Sweet Dee',
      screen_name: 'sweetdeethecat',
      location: 'Mankato, MN',
      description: 'meow',
      url: null,
      entities: [Object],
      protected: false,
      followers_count: 3,
      friends_count: 1,
      listed_count: 0,
      created_at: 'Tue Jan 14 22:41:15 +0000 2014',
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 28,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '000000',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/423224104255111168/Vq_-ogaC_normal.jpeg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/423224104255111168/Vq_-ogaC_normal.jpeg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/2291790446/1411088008',
      profile_link_color: 'A03B27',
      profile_sidebar_border_color: '000000',
      profile_sidebar_fill_color: '000000',
      profile_text_color: '000000',
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'und'
  }, {
    created_at: 'Sat Apr 15 16:42:59 +0000 2017',
    id: 853287547082027000,
    id_str: '853287547082027008',
    text: '@mknepprath @bout_bot #throw?',
    truncated: false,
    entities: {
      hashtags: [Object],
      symbols: [],
      user_mentions: [Object],
      urls: []
    },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: 853287372842258400,
    in_reply_to_status_id_str: '853287372842258434',
    in_reply_to_user_id: 15332057,
    in_reply_to_user_id_str: '15332057',
    in_reply_to_screen_name: 'mknepprath',
    user: {
      id: 2291790446,
      id_str: '2291790446',
      name: 'Sweet Dee',
      screen_name: 'sweetdeethecat',
      location: 'Mankato, MN',
      description: 'meow',
      url: null,
      entities: [Object],
      protected: false,
      followers_count: 3,
      friends_count: 1,
      listed_count: 0,
      created_at: 'Tue Jan 14 22:41:15 +0000 2014',
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 28,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '000000',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/423224104255111168/Vq_-ogaC_normal.jpeg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/423224104255111168/Vq_-ogaC_normal.jpeg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/2291790446/1411088008',
      profile_link_color: 'A03B27',
      profile_sidebar_border_color: '000000',
      profile_sidebar_fill_color: '000000',
      profile_text_color: '000000',
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'und'
  }, {
    created_at: 'Sat Apr 15 16:14:04 +0000 2017',
    id: 853280271868801000,
    id_str: '853280271868801024',
    text: '@bout_bot @mknepprath #throw',
    truncated: false,
    entities: {
      hashtags: [Object],
      symbols: [],
      user_mentions: [Object],
      urls: []
    },
    source: '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
    in_reply_to_status_id: 851671783669473300,
    in_reply_to_status_id_str: '851671783669473280',
    in_reply_to_user_id: 2578652522,
    in_reply_to_user_id_str: '2578652522',
    in_reply_to_screen_name: 'bout_bot',
    user: {
      id: 2291790446,
      id_str: '2291790446',
      name: 'Sweet Dee',
      screen_name: 'sweetdeethecat',
      location: 'Mankato, MN',
      description: 'meow',
      url: null,
      entities: [Object],
      protected: false,
      followers_count: 3,
      friends_count: 1,
      listed_count: 0,
      created_at: 'Tue Jan 14 22:41:15 +0000 2014',
      favourites_count: 0,
      utc_offset: null,
      time_zone: null,
      geo_enabled: false,
      verified: false,
      statuses_count: 28,
      lang: 'en',
      contributors_enabled: false,
      is_translator: false,
      is_translation_enabled: false,
      profile_background_color: '000000',
      profile_background_image_url: 'http://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_image_url_https: 'https://abs.twimg.com/images/themes/theme1/bg.png',
      profile_background_tile: false,
      profile_image_url: 'http://pbs.twimg.com/profile_images/423224104255111168/Vq_-ogaC_normal.jpeg',
      profile_image_url_https: 'https://pbs.twimg.com/profile_images/423224104255111168/Vq_-ogaC_normal.jpeg',
      profile_banner_url: 'https://pbs.twimg.com/profile_banners/2291790446/1411088008',
      profile_link_color: 'A03B27',
      profile_sidebar_border_color: '000000',
      profile_sidebar_fill_color: '000000',
      profile_text_color: '000000',
      profile_use_background_image: false,
      has_extended_profile: false,
      default_profile: false,
      default_profile_image: false,
      following: false,
      follow_request_sent: false,
      notifications: false,
      translator_type: 'none'
    },
    geo: null,
    coordinates: null,
    place: null,
    contributors: null,
    is_quote_status: false,
    retweet_count: 0,
    favorite_count: 0,
    favorited: false,
    retweeted: false,
    lang: 'und'
  }
]

module.exports = tweets
